version: "3"
services: 
  frontend:       
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
  backend:
    links:
      - database      
    environment:
       DATABASE_URI: mysql+pymysql://root:password@database:3306/users 
       SECRET KEY: password      
    depends_on:
      - database
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 5001:5001
  database:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password    
    volumes:
      - ./mysql-data:/var/lib/mysql:rw     
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
volumes:
  mysql-data: